@NativeAot.WebApp_HostAddress = http://localhost:5116

GET {{NativeAot.WebApp_HostAddress}}/todos/
Accept: application/json

###

GET {{NativeAot.WebApp_HostAddress}}/todos/1
Accept: application/json

###
